---
- hosts: node1
  become: true
  vars:
    nexus_version: 3 
    nexus_download_url: https://download.sonatype.com/nexus/{{nexus_version}}/latest-unix.tar.gz
    nexus_download_dest: /tmp/nexus-{{nexus_version}}-bundle.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /usr/local/nexus

  tasks:

  - name: install wget
    yum: pkg='wget' state=installed

  - name: install jdk 7
    yum: pkg='java-1.8.0-openjdk' state=installed

  - name: create "nexus" group
    group: name=nexus 
    

  - name: create "nexus" user
    user: name=nexus group=nexus 
    

  - name: download nexus
    get_url: url={{nexus_download_url}} dest={{nexus_download_dest}}
    register: nexus_download

  - name: create {{nexus_extracted_dir}} directory
    file: path={{nexus_extracted_dir}} state=directory
    when: nexus_download.changed
   

  - name: extract nexus to {{nexus_extracted_dir}}
    command: tar xzf {{nexus_download_dest}} -C {{nexus_extracted_dir}} --strip-components=1
    when: nexus_download.changed
    

  - name: move nexus to {{nexus_dir}} directory
    command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
    when: nexus_download.changed
    

  - name: remove {{nexus_extracted_dir}} directory
    command: rm -rf {{nexus_extracted_dir}}
    when: nexus_download.changed
    

  - name: make {{nexus_dir}} directory property of "nexus" user/group
    file: path={{nexus_dir}} group=nexus owner=nexus recurse=true
    

  - name: make nexus runned by "nexus" user
    lineinfile: dest={{nexus_dir}}/bin/nexus.rc regexp="#run_as_user=" line="run_as_user=nexus" backrefs=true
    

  - name: set NEXUS_HOME
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{nexus_dir}}" backrefs=true
    

  - name: create nexus piddir
    file: path=/var/run/nexus state=directory group=nexus owner=nexus
    

  - name: set nexus pidir
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true
    
  - name: Change file ownership, group and permissions
    file: path={{nexus_dir}} owner=nexus group=nexus mode='1777'
   

  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/etc/init.d/nexus state=link

  - name: start nexus
    service: name=nexus state=started pattern={{nexus_dir}}
    
